# Generated by Django 2.0.5 on 2018-08-26 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('createTime', models.DateField(auto_created=True, auto_now_add=True)),
                ('nickname', models.CharField(max_length=200, verbose_name='用户名')),
                ('openid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='', max_length=200, null=True, upload_to='', verbose_name='头像')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, null=True, verbose_name='性别')),
                ('phone', models.CharField(default='', max_length=11, null=True, verbose_name='电话')),
                ('vip', models.BooleanField(default=False, verbose_name='是否会员')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='介绍')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('like_num', models.IntegerField(default=0, verbose_name='喜欢数量')),
                ('is_share', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('big_images', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='原图')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('sub_title', models.CharField(max_length=200, verbose_name='副标题')),
                ('desc', models.CharField(max_length=200, verbose_name='图片介绍')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('tags', models.CharField(max_length=200, verbose_name='标签')),
                ('price', models.FloatField(default=0, verbose_name='费用')),
                ('vip_price', models.FloatField(default=0, verbose_name='vip费用')),
                ('is_collect', models.IntegerField(default=0, verbose_name='是否收藏')),
                ('is_like', models.IntegerField(default=0, verbose_name='是否喜欢')),
                ('is_buy', models.IntegerField(default=0, verbose_name='是否喜欢')),
                ('collect_number', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('like_number', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('buy_number', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('buy_users', models.ManyToManyField(blank=True, null=True, related_name='购买用户', to='photo.Account')),
                ('collect_users', models.ManyToManyField(blank=True, null=True, related_name='收藏用户', to='photo.Account')),
                ('competition', models.ManyToManyField(blank=True, to='photo.Competition', verbose_name='赛事')),
                ('like_users', models.ManyToManyField(blank=True, null=True, related_name='喜欢用户', to='photo.Account')),
                ('user', models.ManyToManyField(blank=True, null=True, to='photo.Account', verbose_name='创建用户')),
            ],
        ),
    ]
