# Generated by Django 2.0.5 on 2018-08-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180827_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='照片地址')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='photo.Photo', verbose_name='创建用户'),
        ),
    ]
