# Generated by Django 2.0.5 on 2018-08-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180828_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='s_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='水印照片地址'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='photo.Photo', verbose_name='照片'),
        ),
    ]
