# Generated by Django 2.0.5 on 2018-08-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180828_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photolist',
            name='big_images',
        ),
        migrations.AddField(
            model_name='photolist',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='photo.Photo', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='介绍'),
        ),
    ]
