# Generated by Django 2.0.5 on 2018-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20180828_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='照片高'),
        ),
        migrations.AddField(
            model_name='photo',
            name='s_height',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='照片高'),
        ),
        migrations.AddField(
            model_name='photo',
            name='s_width',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='照片宽'),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='照片宽'),
        ),
    ]
