# Generated by Django 2.0.5 on 2018-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20180925_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='照片高'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='s_height',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='照片高'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='s_width',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='照片宽'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='照片宽'),
        ),
    ]
