# Generated by Django 2.0.5 on 2018-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20180925_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_buy',
            field=models.IntegerField(default=0, null=True, verbose_name='是否喜欢'),
        ),
    ]
